# Generated by Django 3.2.13 on 2022-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
